export const actionTypes = {
  GET_POEMS: 'GET_POEMS',
  GET_NEW_POEM: 'GET_NEW_POEM',
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_FAILED: 'FETCH_FAILED',
  FETCH_POEMS_SUCCEED: 'FETCH_POEMS_SUCCEED',
  FETCH_NEW_POEM_SUCCEED: 'FETCH_NEW_POEM_SUCCEED'
};
