export const actionTypes = {
  GET_POEMS: 'GET_POEMS',
  GET_RIMED_POEM: 'GET_RIMED_POEM',
  GET_RIMED2_POEM: 'GET_RIMED2_POEM',
  GET_RANDOM_POEM: 'GET_RANDOM_POEM',
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_FAILED: 'FETCH_FAILED',
  FETCH_POEMS_SUCCEED: 'FETCH_POEMS_SUCCEED',
  FETCH_RANDOM_POEM_SUCCEED: 'FETCH_RANDOM_POEM_SUCCEED',
  FETCH_RIMED_POEM_SUCCEED: 'FETCH_RIMED_POEM_SUCCEED',
  FETCH_RIMED2_POEM_SUCCEED: 'FETCH_RIMED2_POEM_SUCCEED'
};
