export const actionTypes = {
  GET_POEMS: 'GET_POEMS',
  GET_VERSO: 'GET_VERSO',
  GET_ESTROFA: 'GET_ESTROFA',
  GET_POEMA: 'GET_POEMA',
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_FAILED: 'FETCH_FAILED',
  FETCH_POEMS_SUCCEED: 'FETCH_POEMS_SUCCEED',
  FETCH_VERSO_SUCCEED: 'FETCH_VERSO_SUCCEED',
  FETCH_ESTROFA_SUCCEED: 'FETCH_ESTROFA_SUCCEED',
  FETCH_POEMA_SUCCEED: 'FETCH_POEMA_SUCCEED'
};

export const dateFormatOptions = {
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'numeric'
};
